### ISSUE TITLE
Signup/jobseeker: Education Status Options Update

### ISSUE THREAD

**Issue by theGaryLarson** [Computing-For-All/nextjs-issue-tracker#63]
No one creating a jobseeker account should be denied access to creating an account as our mission is to close the skills gap between education and employment. Those not ready for employment will be directed toward training providers and be viewable by training providers for potential recruitment in an upcoming release.

### Part I
![Image](https://github.com/user-attachments/assets/cdc673e3-7f29-4f29-8c65-22e40ce32f6e)

#### Update the section in the image. 
- [ ] Title: "Work Experience" 
- [ ] Question: "Do you have previous technical work experience?" yes/no
>Note: Any data manipulation for a jobseeker that would promote their status needs to adjust the pool category accordingly.
- [ ] Do not block account creation for any jobseeker

### Part II

- [ ] Update jobseekers table with a flag for technical work experience.
- [ ] Create an API route to update tech work experience and connect to frontend from signup/jobseeker page
- [ ] Further filter Jobseeker listview query to only show jobseekers from pool1 as recommended
- [ ] pool2 shows on the listview but is not recommended
- [ ] pool3 jobseekers will not show up to employers at all but rather will be displayed to educators/training providers for potential recruitment

#### Related Issues
- #64

**Comment by theGaryLarson** [comment]
@Gabe-Bryan  I updated the description here after discussing with Maria. There will no longer be an ineligible page. I will create server function we will use on profile completion to assign jobseeker to a pool based on data inputs.

**Comment by rorosaurus** [comment]
After discussion with Gary, removing the work experience from the jobseeker signup page entirely, since that will be computed based on profile information in his upcoming change.

Listview API call has been updated to specify filtering by pools 1 & 2
